#add stages here 
stages:
  data_preparation:
    cmd: python src/stage_01_prepare_data.py
    deps:
    - src/stage_01_prepare_data.py
    - src/utils
    - data/data.xml
    outs:
    - artifacts/prepared

  feature_extraction:
    cmd: python src/stage_02_feature_extraction.py
    deps:
    - src/stage_02_feature_extraction.py
    - src/utils
    - artifacts/prepared
    outs:
    - artifacts/features